pipeline {
    agent any

    environment {
        APP_DIR = "/home/ubuntu/express-app"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/yourusername/express-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                npm install
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                npm test || true
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                pm2 delete express-app || true
                pm2 start server.js --name express-app
                pm2 save
                '''
            }
        }
    }

    post {
        success {
            echo 'Express Deployment Successful!'
        }

        failure {
            echo 'Express Deployment Failed!'
        }
    }
}