pipeline {
    agent any

    environment {
        APP_DIR = "/home/ubuntu/flask-app"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/yourusername/flask-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest || true
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                pm2 delete flask-app || true
                pm2 start "venv/bin/python app.py" --name flask-app
                pm2 save
                '''
            }
        }
    }

    post {
        success {
            echo 'Flask Deployment Successful!'
        }

        failure {
            echo 'Flask Deployment Failed!'
        }
    }
}